MODEL:
  PRETRAIN_PATH: '/home/ma-user/work/Projects/ReIDZoo_Checkpoints/GhostNet_1_0.pth'
  PRETRAIN_HW_RATIO: 2
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'ghostnet_1_0'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  PRETRAIN_CHOICE: 'self'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5,0.5,0.5]
  PIXEL_STD: [0.5,0.5,0.5]

DATASETS:
  NAMES: ('msmt17')
  ROOT_DIR: ('/home/ma-user/work/Datasets/ImageReID_Datasets/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.0004
  WARMUP_EPOCHS: 20
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'cosine'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 10
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/GhostNet_1_0_MSMT17'