_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    EXTRA_BN: True
    DEPTH: "101x"
    PRETRAIN_PATH: "/home/ma-user/work/Projects/ReIDZoo_Checkpoints/ResNet101_IBN.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

INPUT:
  REA:
    MEAN: [0.0, 0.0, 0.0]
  DO_AUTOAUG: False

SOLVER:
  HEADS_LR_FACTOR: 1.0
  BACKBONE_BN_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: -1

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)
  ROOT: "/home/ma-user/work/Datasets/ImageReID_Datasets"

TEST:
  EVAL_PERIOD: 60

OUTPUT_DIR: "logs/msmt17/ResNet101_IBN_CION_MGN"
